service: kinesis-shard-cfn-macro

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'kinesis:ListShards'
      Resource: '*'

functions:
  # Define Lambda function for macro.
  Dashboard:
    name: kinesis-shard-cfn-macro-dashboard
    handler: dashboard.lambda_handler

resources:
  Resources:
    # Define macro.
    DashboardMacro:
      Type: "AWS::CloudFormation::Macro"
      Properties:
        Name: KinesisShardLevelDashboard
        Description: Macro to generate dashboard for kinesis shard level metrics.
        FunctionName: kinesis-shard-cfn-macro-dashboard
